### ISSUE TITLE
mismatched types at src/lib.rs:969:38 on 1.8.0-nightly (15e9a95a4)

### ISSUE THREAD

**Issue by kellenfujimoto** [dpc/mioco#102]
Fixed under this pull request: https://github.com/dpc/mioco/pull/101

**Comment by dpc** [comment]
Weird. Test suite should catch problems like this. I'll take a look later.

**Comment by kellenfujimoto** [comment]
It appears to be a problem with the version uploaded to `crates.io`. Build succeeds when using the Github repo, but fails when `mioco = "0.2.0"` in the dependencies.

**Comment by dpc** [comment]
Ah. Please use github version for now. There should be a new release soon anyway.

**Comment by dpc** [comment]
New version was released on crates.io.
