### ISSUE TITLE
Change API for `spawn`/`start` to be just like `std::thread`

### ISSUE THREAD

**Issue by dpc** [dpc/mioco#112]
* closures should be of type `FnOnce() -> T`, the `Result<T>` return type is unnecessary
* every closure should be able to return different `T`
* mioco::spawn should return a `JoinHandle`
* mioco::start should return just `Result<T>` of the starting function, just like `JoinHandle::join()`.

**Comment by dpc** [comment]
@troplin @Drakulix

**Comment by troplin** [comment]
mioco::start should return a `io::Result<T>` IMO, as does `JoinHandle::join()`
Otherwise, what would you return on panic or shutdown?

**Comment by dpc** [comment]
Right @troplin . Updated the description.

**Comment by Drakulix** [comment]
Seems reasonable. Although I don't mind the current design.

**Comment by dpc** [comment]
Wasn't that hard.
