### ISSUE TITLE
Error handling for TcpStream::connect to non-listening port

### ISSUE THREAD

**Issue by gnoack** [dpc/mioco#131]
Thanks for your work on Mioco!  This has been a breeze to use so far, apart from this little bug. :)

### Steps to reproduce:
 * Call `mioco::tcp::TcpStream::connect(&addr)` and point it to a non-listening localhost port.
 * It returns an `Ok(socket)` result with a socket object instead of an error.

### Expected behaviour:
 * It should return an error that it couldn't connect.

### Rationale:
I would have assumed that `TcpStream::connect()` should provide a synchronous programming model when invoked from a mioco coroutine.  That would be consistent with what synchronous TCP APIs do.

### Suspicion:
In the mio library, `TcpStream::connect()` is first setting the socket into non-blocking mode and then treating the `EINPROGRESS` error as successful.  ([src/sys/unix/tcp.rs:38](https://github.com/carllerche/mio/blame/master/src/sys/unix/tcp.rs#L38))

Maybe I'm misunderstanding something about the API?  Is there another way in which I can detect this scenario in mioco without doing reads and writes on the socket already?

**Comment by dpc** [comment]
I think this is #42 again. The reason is the simplistic way mioco translates connection to mio connection, yes.

Let me hack on this for a moment...

**Comment by dpc** [comment]
Please reopen if something is wrong with it! I'm always happy to fix bug reports.

**Comment by gnoack** [comment]
Awesome, works great!  Thanks for the quick bugfix! :)
