### ISSUE TITLE
`UnixListener` is not usable.

### ISSUE THREAD

**Issue by SAPikachu** [dpc/mioco#135]
`UnixListener` is currently defined as a newtype, instead of alias of `MioAdapter`, so we can't call `accept()` or `try_accept()` on it. Was this missed when introducing `MioAdapter`, or is there any reason implementing it like that?

**Comment by dpc** [comment]
I'm quite sure it's just my mistake. Feel free to submit a PR, or I'll fix it over the weekend. Sorry for that. :)

**Comment by SAPikachu** [comment]
Just submitted a PR. :)
