### ISSUE TITLE
Mailbox optimizations and features.

### ISSUE THREAD

**Issue by dpc** [dpc/mioco#14]
Current mailbox seems sufficient for a start, but could potentially be optimized.

* [x] lockless implementation (currently using spinlocks)
* [x] ability to send messages in the other direction (currently it's only possible to send them into Coroutines); non-blocking channel into other direction should be enough for starter

**Comment by fantix** [comment]
Supporting `clone()` shall be one of the most wanted features.

**Comment by dpc** [comment]
@fantix : There should be nothing preventing Clone on `MailboxOuterEnd`, it was just overlooked. Please let me know if it works for you, as we don't have any tests for it yet.

**Comment by dpc** [comment]
Or do you need something that would make a copy that is `Send`-able to other threads?

**Comment by dpc** [comment]
Mioco now has channels that work even outside of mioco. They are not completely lockless but should be good enough. Sending messages in other direction is supported by just creating two channels.

**Comment by dpc** [comment]
Also channels are mpsc so sending end can be closed as requested @fantix.
