### ISSUE TITLE
Change the documentation to remove the need for Rust Nightly 

### ISSUE THREAD

**Issue by StyMaar** [dpc/mioco#142]
From the readme:
>
Note: You must be using nightly Rust release. If you're using multirust, which is highly recommended, switch with multirust default nightly command.

From gitter
> Bertram Truong
@bt
Jun 10 14:25
hey guys, i'm starting to use mioco for my application that has TCP threads; i just wanted to ask why Rust nightly is needed
Bertram Truong
@bt
Jun 10 14:32
i seem to be able to run it on 1.9.0
Dawid Ciężarkiewicz
@dpc
Jun 10 18:35
Stable works 

If stable works, it would be cool to remove everything in the documentation that says otherwise.

**Comment by bt** [comment]
+1, yeah that was a bit confusing for me.

**Comment by dpc** [comment]
Fixed. Thanks!
