### ISSUE TITLE
Missing openwrt/mipsel support

### ISSUE THREAD

**Issue by tomsiwik** [dpc/mioco#143]
**nix** builds on openwrt now (mipsel-unknown-linux-musl), **mioco** aswell as **mio** are lacking the new support. Are there any plans to upgrade the dependancies any time soon to extend the platform range? Thank you.

**Comment by dpc** [comment]
I updated mioco deps, and released 0.7.0. Mio is still in 0.5.1, and pulls previous nix release, so I don't if it helps you at all. I plan keep updating mio dependency as it's released. Is there anything else that isn needed to get mipsel support?

**Comment by tomsiwik** [comment]
Thanks for the quick response. I linked the issue on mio's git repo.  I didn't find any old dependency yet that would break the build. Let's just wait for now...

**Comment by dpc** [comment]
Not actionable from my side, I guess, so closing.
