### ISSUE TITLE
Manual coroutine scheduling.

### ISSUE THREAD

**Issue by dpc** [dpc/mioco#36]
TODO:
 * [x] #68 

Original description:

https://www.reddit.com/r/rust/comments/3j1z78/mio_coroutines_010_released/culos3u: " For example, because mioco is single-threaded right now, I'd love to ask mioco which tasks are pending, so I could implement a scheduler and move work to a different thread if I needed. Right now work has to be scheduled more coarsely up-front (such as moving "work units" into a shared queue and then using co-routines to drain the queue, instead of scheduling co-routines themselves). "

**Comment by dpc** [comment]
Right now I'm only wondering how exactly to break the even handling to let user plug custom logic.

Currently mioco just let the mio's `EventLoop` drive the control flow. This can be changed and instead of resuming coroutine on every event, runnable coroutines would be put to a per-thread queue, and routines would run custom logic to drive the order of actually resuming coroutines.

My doubt is -- how often should I call such function: on every wakeup, on every `tick()`, after fixed time?

I have no experience in userland scheduling designs like this. I think I can implement something that would work, but would probably be suboptimal, or not very ergonomic.

**Comment by dpc** [comment]
@polyfractal , any thoughts?

**Comment by polyfractal** [comment]
Unfortunately, I have very little with userland scheduling either.  And I'm still learning mioco + mio, so my suggestions come with a healthy dose of salt :)

Perhaps you could allow the user to inject a HandlerFactory (or similar) into Mioco on instantiation?  That would let them write their own Handler implementation and make performance their responsibility.  Maybe something like this? (almost certainly is incorrect Rust, but hopefully you get the idea)

```rust
trait HandlerFactory {
    fn new(shared : RefHandlerShared) -> mio::Handler;
}

enum HandlerFactoryType {
    Default,
    Custom(HandlerFactory)
}

impl Mioco {
    pub fn new(handler: HandlerFactoryType) -> Self {
        let shared = Rc::new(RefCell::new(HandlerShared::new()));
        let handler = match handler {
            Default => Handler::new(shared.clone()),
            Custom(h) => h::new(shared.clone())
        };

        Mioco {
            event_loop: EventLoop::new().expect("new EventLoop"),
            server: handler,
        }
    }
...
}
```

Then the user could implement their own handler which batches up ready events and deals with them on each tick:

```rust

impl HandlerFactory for MyHandler {
    fn new(shared : RefHandlerShared) -> mio::Handler {
      MyHandler{ ... }
    }
}

impl mio::Handler for MyHandler {
    type Timeout = Token;
    type Message = Token;

    fn ready(&mut self, event_loop: &mut mio::EventLoop<Handler>, token: mio::Token, events: mio::EventSet) {
       // ... queue up the event instead of dispatching it immediately
    }

    fn tick(&mut self, event_loop: &mut mio::EventLoop<Self>) {
        // ... re-prioritize ready events, dispatch, pass them to other threads, etc
    }
  ...
}
```

Do you think something like that would work?  I do like how Mioco is not very opinionated and basically provides a robust single threaded API which you can use to build multi-threaded apps.  Giving the ability to inject a custom handler would give flexibility when needed, but not saddle the default implementation with lots of details.

**Comment by dpc** [comment]
So you basically think that `tick` is the place where scheduling logic should take place? Ok. I guess it makes sense. `tick()` implementation can run as many corotines as it wants, and then return to get another round of events.

I'm not a Rust expert, but I think parametrizing over user provided type is more rustic way to let user implement custom logic. Also, I'm not sure if `mio::Handler` will be the actual trait - it actually has more methods. I would rather expose very similiar but mioco defined trait.

I think I have some rough idea that I could give a shot at some point.

**Comment by dpc** [comment]
Also, in `ready()` mioco will only provide (ids of?) Coroutines that got ready, not the raw events. The actual logic tracking which raw events wakes which coroutine, is exactly what mioco is doing, so I don't think user wants to override that. It's just the order and timing of actual resuming coroutine that I want to put in user hands.

**Comment by polyfractal** [comment]
> So you basically think that tick is the place where scheduling logic should take place?

Yeah, that was my first gut instinct.  Otherwise the scheduler won't know what events are available for (re-)scheduling

> I'm not a Rust expert, but I think parametrizing over user provided type is more rustic way to let user inject custom logic.

Not sure I understand, but I'll agree with whatever you think... you have more Rust experience than me! :)  My main motivation in providing a "factory" is that I don't want to, as the user, instantiate a new Handler every time I spawn a new coroutine.

If you could pass in a trait object and instantiate off that, it'd definitely be cleaner than some java-esque intermediary factory :)

> Also, in ready() mioco will only provide (ids of?) Coroutines that got ready, not the raw events. 

Yeah, agreed.  The user would still want mioco to do the actual dispatching of events, etc.  So they should just be provided with a list of IDs, perhaps a way to attach custom metadata to each ID (e.g. so they can add a "priority" value or name, etc) too

**Comment by dpc** [comment]
> perhaps a way to attach custom metadata to each ID (e.g. so they can add a "priority" value or name, etc) too

Good idea.

**Comment by dpc** [comment]
As a part of #37 the design changed somewhat to provide multi-threading support.

**Comment by dpc** [comment]
With userdata complete, I think this can be closed.
