### ISSUE TITLE
Multithreading support?

### ISSUE THREAD

**Issue by dpc** [dpc/mioco#37]
Implement multithreading support.

Some TODO-notes:

* [x] Should new Coroutines be started by default on the thread of the parent-Coroutine or should there be a `Scheduler` (or `SchedulerThread`) function that can override this?
* [x] Default `FiFoScheduler` should randomly distribute new Coroutines between it's threads. Otherwise everything will be executed on first thread, which kind of misses the whole point.
* [x] What should be the exit conditions for whole Mioco server, and it's threads. Should `SchedulerThread` take an argument providing an API to shoot down thread/everything? Or does it matter at all in real life software?
* [ ] How to accommodate Idle Coroutines from #39 ? Coroutines should be able to call `MiocoHandle::yield()` that puts them into idle state, that is basically like Ready, but not blocked on anything. After `CoroutineControl::resume()` they would appear in `SchedulerThread::ready()` in next tick batch, or should `SchedulerThread` deal with them distinctly.

**Comment by bfrog** [comment]
I'd highly recommend reading up on how erlang does this, as it does an amazing job of doing the right thing seemingly almost all the time. http://jlouisramblings.blogspot.com/2013/01/how-erlang-does-scheduling.html

**Comment by dpc** [comment]
@bfrog Thanks for the read. I actually hope to completely offload the scheduling logic and let it be taken care by user. Mioco might provide some sane defaults.

**Comment by dpc** [comment]
I've pushed an smp branch with most important parts implemented, yet testing, polishing and some details are missing. But it basically shows that all the bits can be glued together within the current design without structural problems. In a week or two, I hope to have it all working.

User will be able to implement `Scheduler` trait: https://github.com/dpc/mioco/blob/smp/src/lib.rs#L1467, which job is to glue together and spawn `SchedulerThread`-implementing structs: https://github.com/dpc/mioco/blob/smp/src/lib.rs#L1474 . Coroutines can be migrated using `migrate()`: https://github.com/dpc/mioco/blob/smp/src/lib.rs#L554

**Comment by dpc** [comment]
This is done. The idle coroutines have their own issue so closing this one.
