### ISSUE TITLE
Echo example does not compile (new-design branch)

### ISSUE THREAD

**Issue by carlopires** [dpc/mioco#4]
I just found this project and tried to compile it to see if it works. So I created a Cargo.toml like this:

    [package]
    name = "echo"
    version = "0.1.0"
    authors = ["Carlo Pires <carlopires@....com>"]
    
    [dependencies.mio]
    git = "https://github.com/carllerche/mio"
    
    [dependencies.mioco]
    git = "https://github.com/dpc/mioco"
    branch = "new-design"

When running, I get the following error:

    $ cargo build
        Updating registry `https://github.com/rust-lang/crates.io-index`
     Downloading winapi v0.1.23
     Downloading tempdir v0.3.4
     Downloading spin v0.3.1
     Downloading bytes v0.2.10
     Downloading regex v0.1.41
     Downloading log v0.3.1
     Downloading bitflags v0.1.1
     Downloading clock_ticks v0.0.5
     Downloading mmap v0.1.1
     Downloading gcc v0.3.11
     Downloading env_logger v0.3.1
     Downloading aho-corasick v0.3.0
     Downloading slab v0.1.2
     Downloading regex-syntax v0.2.1
     Downloading memchr v0.1.3
     Downloading rand v0.3.8
     Downloading coroutine v0.3.2
     Downloading nix v0.3.9
     Downloading libc v0.1.8
       Compiling spin v0.3.1
       Compiling tempdir v0.3.4
       Compiling aho-corasick v0.3.0
       Compiling coroutine v0.3.2
    /home/carlopires/.cargo/registry/src/github.com-1ecc6299db9ec823/spin-0.3.1/src/mutex.rs:112:15: 112:17 error: expected identifier, found keyword `fn`
    /home/carlopires/.cargo/registry/src/github.com-1ecc6299db9ec823/spin-0.3.1/src/mutex.rs:112     pub const fn new(user_data: T) -> Mutex<T>
                                                                                                           ^~
    /home/carlopires/.cargo/registry/src/github.com-1ecc6299db9ec823/spin-0.3.1/src/mutex.rs:112:18: 112:21 error: expected `:`, found `new`
    /home/carlopires/.cargo/registry/src/github.com-1ecc6299db9ec823/spin-0.3.1/src/mutex.rs:112     pub const fn new(user_data: T) -> Mutex<T>
                                                                                                              ^~~
       Compiling mio v0.4.1 (https://github.com/carllerche/mio#478cef3f)
    Build failed, waiting for other jobs to finish...
    Could not compile `spin`.

    $ rustc --version
    rustc 1.1.0 (35ceea399 2015-06-19)

So, there is a problem with my rust ? Am I missing something?

**Comment by carlopires** [comment]
I forgot to mention that I'm trying to build the echo.rs example

**Comment by dpc** [comment]
I don't think `mioco` will compile on anything different than nightly branch ATM. If you're using `multirust` (which I highly recommend), try`multirust default nightly` and try again.

**Comment by dpc** [comment]
In case you have any troubles let me know on: https://gitter.im/dpc/mioco . I have it beeping on my phone, so I can respond faster. I'm closing this one for now. Cheers!

**Comment by carlopires** [comment]
I used the nightly build from rust-lang site and it compiled fine. It would be good to add a note about this on readme. 

    $ rustc --version
    rustc 1.3.0-nightly (69ca01256 2015-07-23)

**Comment by dpc** [comment]
Yeap, I already did so on the new-desing branch.
