### ISSUE TITLE
Implement "connect_wait()".

### ISSUE THREAD

**Issue by dpc** [dpc/mioco#42]
I found a workaround for the connect problem: I can do s.with_raw(|s| s.take_socket_error()) and inspect that after the stream is writeable
not ideal, but it works
Mioco could expose that ...
This could be named "connect_wait()" or something.

**Comment by polyfractal** [comment]
I took a stab at it here, but failed to appease the compiler.  Mio's `connect()` function needs to take ownership of the socket, but we can only borrow it from the RefCell.

https://github.com/polyfractal/mioco/commit/04d1ef80848360714d81d32ba07768c92e28f60e

I'm too new at Rust to understand how to fix this, I'm afraid :(

**Comment by dpc** [comment]
As connect is non-blocking and has two forms: TcpStream::connect(addr) and TcpSocket::connect(self, addr), I don't think there's a good way to help with that at mioco level. I think that dpc/mioco@864456a is the best we can do ATM.

**Comment by polyfractal** [comment]
Yeah, I'm not sure how to resolve it given Mio's api (and my lack of Rust knowledge).  Your commit does makes the API a bit more friendly:

```rust
let (stream, mut complete) = socket.connect(&addr).unwrap();
let stream = mioco.wrap(stream);

if !complete {
    complete = match stream.connect_wait() {
        Ok(_) => true,
        Err(e) => {
            debug!("err: {:?}", e);
            false
        }
    }
}
```

I'm not sure about the long-term utility though.  It's not technically related to `connect()` at all, just chaining a select_write + error polling.  It's also a little confusing that you have to call `connect()` yourself, then call `connect_wait()` (after wrapping it) 

Perhaps just expose a `take_error()` method instead?

```rust
if !complete {
    mioco.select_write();
    complete = match stream.take_error() {
        Ok(_) => true,
        Err(e) => {
            debug!("err: {:?}", e);
            false
        }
    }
}
```

Or a little bit different, how about a static `connect_stream()` helper method on `mioco` itself?  E.g. something like this:

```rust
impl Mioco {
    // ...
   
    pub fn connect_stream(&mut mioco: MiocoHandle, addr: SocketAddr) -> Result<EventSource<TcpStream>> {
        let (stream, complete) = TcpStream::connect(&addr);

        let stream = mioco.wrap(stream);
        if (complete) {
            return Ok(stream);
        }

        mioco.select_write_from(&[stream.id()]);
        stream.with_raw(|s| s.take_socket_error()).and_then(|s| Ok(s))
    }
}
```
Which would be used like this:

```rust
// Blocks and returns a connected, wrapped stream or an error
match mioco::connect_stream(mioco, &addr) {
    Ok(s) => debug!("got a stream"),
    Err(e) => debug!("Error connecting: {}", e)
}
```

**Comment by dpc** [comment]
@carllerche is considering dropping the bool argument from TcpStream::connect() return value, BTW.

**Comment by 3Hren** [comment]
Hi!

Any progress on this issue?

**Comment by dpc** [comment]
Not really. I wanted to tackle multithreading and custom schedulers refactoring first, since this is only a convenience function, so it does not block anyone.

Also, there's this: https://github.com/carllerche/mio/pull/262

**Comment by dpc** [comment]
I believe recent refactoring and #84 fixed it.
