### ISSUE TITLE
event loop runtimes benchmarks and mioco timeouts

### ISSUE THREAD

**Issue by danoctavian** [dpc/mioco#46]
You might want to check this out.

https://github.com/danoctavian/c10k-bench

I've gathered together some event driven runtimes and implemented an echo server for each.

For rust, i've put in mioco and coio.

The benchmark is crude and probably flawed. Also i'm not measuring latency average and standard deviation per request.

Any feedback is greatly welcome, i would like to make it a more solid benchmark, but i don't have much exp with benchmarks.

The trouble i am encountering with mioco is that requests time out when running 3000 connections simultaneously for 30s. if i run 128 threads each sequentially doing connections for 30s it completes.

The benching code is here:
https://github.com/danoctavian/c10k-bench/blob/master/bencher/src/Lib.hs

Thank you!

**Comment by dpc** [comment]
Hi. Can you try increasing slab size: https://github.com/dpc/mioco/blob/master/src/lib.rs#L1216 ?

**Comment by danoctavian** [comment]
yeah sure thing, i'll play around and let you know!

**Comment by dpc** [comment]
Hi, I've just pushed new version that implements multithreading, and the original problem you were hitting should be fixed too. It's working for me with go-bencher, I don't use haskell, so I haven't tried the haskell bencher.

**Comment by danoctavian** [comment]
just verified. now works without failing. Thanks!

**Comment by dpc** [comment]
Well, now you've got to update the benchmarks. :P

**Comment by dpc** [comment]
I've created an issue in the original repo. Closing this one.
