### ISSUE TITLE
Get rid of Clone requirement for type T of MailboxOuterEnd

### ISSUE THREAD

**Issue by 3Hren** [dpc/mioco#48]
According to the https://doc.rust-lang.org/nightly/std/sync/mpsc/struct.Sender.html there is no need for `T` to be `Clone`, but http://dpc.pw/mioco/mioco/struct.MailboxOuterEnd.html requires it.

**Comment by dpc** [comment]
I naively thought that `#[derive(Clone)] will do the right thing. Is #51 what you need?

**Comment by 3Hren** [comment]
Yep, thanks!
