### ISSUE TITLE
Unable to run without spawning at least 1 native thread

### ISSUE THREAD

**Issue by 4xrsJCr9** [dpc/mioco#59]
It would be useful to be able to pass ```0``` to ```start_threads()``` so that no extra threads are spawned. Currently, doing so results in a panic:

```rust
thread '<main>' panicked at 'called `Option::unwrap()` on a `None` value', ../src/libcore/option.rs:366
stack backtrace:
   1:     0x5641ef0a4130 - sys::backtrace::tracing::imp::write::h5839347184a363c1Tnt
   2:     0x5641ef0a6685 - panicking::log_panic::_<closure>::closure.39955
   3:     0x5641ef0a60d1 - panicking::log_panic::hcde6d42710304abbWnx
   4:     0x5641ef093f63 - sys_common::unwind::begin_unwind_inner::h4039843fef6bffefYgs
   5:     0x5641ef094618 - sys_common::unwind::begin_unwind_fmt::hbbea9d3fc97574084fs
   6:     0x5641ef0a3801 - rust_begin_unwind
   7:     0x5641ef0d37df - panicking::panic_fmt::h6c78ce0128588a957HK
   8:     0x5641ef0cf8b8 - panicking::panic::h98c7cbfc94ff8f45EGK
   9:     0x5641eee1513f - option::_<impl>::unwrap::unwrap::h16152199457913105795
                        at ../src/libcore/macros.rs:20
  10:     0x5641eee047c8 - _<impl>::start::start::h12834185189550730189
                        at /home/rust/.multirust/toolchains/nightly/cargo/git/checkouts/mioco-c9a859598988616b/master/src/lib.rs:2100
  11:     0x5641eee04149 - start_threads::start_threads::h7114804408540994820
                        at /home/rust/.multirust/toolchains/nightly/cargo/git/checkouts/mioco-c9a859598988616b/master/src/lib.rs:2368
  12:     0x5641eee03ebb - app::net2::main::hed6819897c005210Byc
                        at src/app/net2.rs:12
  13:     0x5641eee17e19 - main::hf894a5ce1ff19dc5aBc
                        at src/main.rs:60
  14:     0x5641ef0a5e14 - sys_common::unwind::try::try_fn::h2957776305083477838
  15:     0x5641ef0a3668 - __rust_try
  16:     0x5641ef0a5aaf - rt::lang_start::h0e35413b64fe04744kx
  17:     0x5641eee19619 - main
  18:     0x7fe17d7f060f - __libc_start_main
  19:     0x5641eece5ae8 - _start
  20:                0x0 - <unknown>
```

I can't think of any reason why the main thread (or the the thread on which ```start_threads()``` is called) is not used to execute coroutines; am I missing something?

**Comment by dpc** [comment]
Right. The first mioco thread should be the current one.

**Comment by dpc** [comment]
Is this really a big issue for you? I looked at the code, and the reason to do this the way it is currently is simplicity.

**Comment by 4xrsJCr9** [comment]
It isn't a big issue. My primary concern was related to the less than ideal interaction between threads and signal handlers, but that can be worked around.

Thanks for looking into it.

**Comment by Drakulix** [comment]
Its actually an issue for me. Many ffi-libraries rely on having access to the main thread. With mioco this is impossible, as the main-thread will be always joining all worker threads, instead of becoming a worker thread itself.
I think it would be quite easily to implement by moving the thread creation out of spawn_thread into start (and probably renaming spawn_thread in the process to something like thread_loop). Then start could call that function itself at the end.
Would you interesting in a pull request for this?
