### ISSUE TITLE
Attach custom data to each Coroutine for Scheduling purposes.

### ISSUE THREAD

**Issue by dpc** [dpc/mioco#68]
Requested in #36 . Right now `SchedulerThread` can only get the following information about each coroutine:

* id - through `CoroutineControl::id()`
* if it's blocked on `yield_now()` - through `CoroutineControl::is_yielding()`

Being able to attach some custom data (eg. priorities) might greatly simplify custom schedulers job.

**Comment by Drakulix** [comment]
I suggest adding an associated type to the ```SchedulerThread``` trait (maybe named ```Hint``` or something similar), that needs to implement ```Default```. Like that the ```MiocoHandle::spawn``` function may continue to work and custom schedulers might be used without knowing their details. ```MiocoHandler::spawn``` could then be complemented by a ```MiocoHandler::spawn_with``` function or similar that takes an actual ```Hint```.
