### ISSUE TITLE
lots_of_event_sources fails on my system.

### ISSUE THREAD

**Issue by Drakulix** [dpc/mioco#73]
I am not sure what is causing this, but the current master branch tests do not succeed on my system.
I have already tried to update Rust to latest nightly, run cargo clean and cargo update.

Log:
```
...
test tests::exit_notifier_simple ... ok
test tests::lots_of_event_sources ... FAILED
test tests::million_coroutines ... ignored
test tests::long_chain ... ok
...

---- tests::lots_of_event_sources stdout ----
	thread 'tests::lots_of_event_sources' panicked at 'explicit panic', src/tests.rs:200
thread 'tests::lots_of_event_sources' panicked at 'assertion failed: *finished_ok.lock().unwrap()', src/tests.rs:210


failures:
    tests::lots_of_event_sources

test result: FAILED. 26 passed; 1 failed; 1 ignored; 0 measured

```

**Comment by dpc** [comment]
Can you run with `RUST_LOG=mioco RUST_BACKTRACE=1`?

**Comment by Drakulix** [comment]
failures:

---- tests::lots_of_event_sources stdout ----
	thread 'tests::lots_of_event_sources' panicked at 'explicit panic', src/tests.rs:200
stack backtrace:
   1:     0x564a2a499200 - sys::backtrace::tracing::imp::write::h5bd2cbd5ee096950M0t
   2:     0x564a2a49b815 - panicking::log_panic::_<closure>::closure.41427
   3:     0x564a2a49b2d7 - panicking::log_panic::hb5ddab7e6279e99d17x
   4:     0x564a2a48e203 - sys_common::unwind::begin_unwind_inner::hc8bc8f561ea07eedlTs
   5:     0x564a2a303da7 - sys_common::unwind::begin_unwind::begin_unwind::h7272200411219993980
                        at ../src/libstd/sys/common/unwind/mod.rs:237
   6:     0x564a2a37abb2 - tests::lots_of_event_sources::_<closure>::closure.15506
                        at /home/drakulix/Projects/mioco/<std macros>:3
   7:     0x564a2a379d4a - boxed::_<impl>::call_box::call_box::h11466688556503152368
                        at ../src/liballoc/boxed.rs:541
   8:     0x564a2a31ef8a - _<impl>::spawn::init_fn::_<closure>::closure.13652
                        at src/lib.rs:917
   9:     0x564a2a31e9d1 - std::thread::catch_panic::_<closure>::closure.13647
                        at ../src/libstd/thread/mod.rs:367
  10:     0x564a2a31e9a9 - sys_common::unwind::try::try_fn::try_fn::h8716009638420307813
                        at ../src/libstd/sys/common/unwind/mod.rs:163
  11:     0x564a2a4986a8 - __rust_try
  12:     0x564a2a4954fb - sys_common::unwind::try::inner_try::hd39e736d6d2a03e7TPs
  13:     0x564a2a31e960 - sys_common::unwind::try::try::h15980586775432477219
                        at ../src/libstd/sys/common/unwind/mod.rs:133
  14:     0x564a2a31e720 - thread::catch_panic::catch_panic::h8750498211199299947
                        at ../src/libstd/thread/mod.rs:367
  15:     0x564a2a31d804 - _<impl>::spawn::init_fn::__rust_abi
                        at src/lib.rs:907
  16:     0x564a2a31d75c - _<impl>::spawn::init_fn::hcd61c49185ac55d7Iob
  17:                0x0 - <unknown>
thread 'tests::lots_of_event_sources' panicked at 'assertion failed: *finished_ok.lock().unwrap()', src/tests.rs:210
stack backtrace:
   1:     0x564a2a499200 - sys::backtrace::tracing::imp::write::h5bd2cbd5ee096950M0t
   2:     0x564a2a49b815 - panicking::log_panic::_<closure>::closure.41427
   3:     0x564a2a49b2d7 - panicking::log_panic::hb5ddab7e6279e99d17x
   4:     0x564a2a48e203 - sys_common::unwind::begin_unwind_inner::hc8bc8f561ea07eedlTs
   5:     0x564a2a303da7 - sys_common::unwind::begin_unwind::begin_unwind::h7272200411219993980
                        at ../src/libstd/sys/common/unwind/mod.rs:237
   6:     0x564a2a375182 - tests::lots_of_event_sources::h09414597f05e26dcJhd
                        at /home/drakulix/Projects/mioco/<std macros>:3
   7:     0x564a2a470bd6 - boxed::_<impl>::call_box::call_box::h1440388976974007934
   8:     0x564a2a47363f - sys_common::unwind::try::try_fn::try_fn::h14146497908029864798
   9:     0x564a2a4986a8 - __rust_try
  10:     0x564a2a4954fb - sys_common::unwind::try::inner_try::hd39e736d6d2a03e7TPs
  11:     0x564a2a4739da - boxed::_<impl>::call_box::call_box::h4583084239203220142
  12:     0x564a2a49a183 - sys::thread::_<impl>::new::thread_start::h95308cec67b4d88eeax
  13:     0x7fd5537a84a3 - start_thread
  14:     0x7fd553fa913c - clone
  15:                0x0 - <unknown>

**Comment by Drakulix** [comment]
On a quick node. Running `cargo test lots_of_event_sources` succeeds. Only running all tests with `cargo test` or `make longtest` shows this odd behavior.

**Comment by dpc** [comment]
Oh, I've forgot about this. Is this still affecting you?

**Comment by Drakulix** [comment]
`nowrap` fixed it somehow. `make longtest` runs through without any issues.
