### ISSUE TITLE
Migrate to context-rs v1.0

### ISSUE THREAD

**Issue by zonyitoo** [dpc/mioco#94]
Hey dpc. `context-rs` is moving to `v1.0`, which uses APIs from `Boost.Context` in C++. It is now ready for test, would you mind to migrate to `v1.0`? Because the old implementation is going to be deprecated in the future.

## Benefits

* Much more faster than the previous implementation
* Support various platforms (the previous implementation does not work on x86 with unknown reason)
* Able to pass data when context switching
* Able to provide a callback after context switching (will be called on the other side on a different stack)
* Could be compiled with stable Rust

## How to migrate

APIs in `v1.0` is completely different from the old implementation, so you could start with [examples/basic.rs](https://github.com/zonyitoo/context-rs/blob/1.0/examples/basic.rs). Main differences are:

* `Context::new` will return a pointer instead of a struct of registers. Data is stored on the stack.
* Resuming a `Context` will return a new pointer to the `Context` after it comes back.

*NOTE: v1.0 is still in experimental stage yet. Request for comments!*

**Comment by dpc** [comment]
Nice! I'll try to switch and will give you my feedback.

**Comment by dpc** [comment]
Hi @zonyitoo , I have initial stuff done. Tests are passing, performance is as good as before (well, noticeably slower, see below).

Some quick feedback:

I was a bit confused by `Transfer`: I wasn't sure what to store (`Context` or `Transfer`) and relation between them were not clear to me initially. I wonder if having a pub struct for two values is necessary. `init_fn` could take `(Context, usize)`, `resume` would return `(Context, usize)` and `Transfer` could be an implementation detail. The problem with that is that `let t = t.context.resume(x);` is not a one-liner.

    let (newcontext, data) = context.resume(x);
    context = newcontext;


I'd like to have something that can store any Stack. Right now I have to store ProtectedFixedSizeStack, even though it could be really any other version. So either an enum or a trait, depending on if the 3rd parties should be allowed to implement their own stack types.

As Context is non-copyable, I had to use `Option<Context>` where I previously had just `Context`. That's not the end of the world, but I wonder if it's necessary. It seem to cost some perf (unwraps() + additional data).

The performance on `cheating-http-server` which I use as a microbenchmark of context switching and main hot-path is slightly lower now. I think it's the `Option<Context>`. At very least `Context` should be `NonZero` so the `Option` can inline it.

Overall I like the changes, and I will look for ways to utilize a free return data, that I get every time switching out of a coroutine. I was hopping for some performance speedup, but now slowdown is good enough for me. :D

**Comment by Drakulix** [comment]
@dpc If data is unimportant and you want a one-liner:
```
context = context.result(x).0;
```

**Comment by zonyitoo** [comment]
@dpc For the `Transfer` struct, you can destruct it with

```rust
let Transfer { context: ctx, data: data } = context.resume(0);
```

Because you **have to** retrieve a new `Context` from the `context.resume(0)`, so I made the `Context` non-Copiable, which will force you to get a new `Context` from the `Transfer`.

Actually, you could find that the prototype of [`Context::new`](https://github.com/zonyitoo/context-rs/blob/1.0/src/context.rs#L79) is

```rust
pub fn new(stack: &Stack, f: ContextFn) -> Context
```

and the [`Stack`](https://github.com/zonyitoo/context-rs/blob/1.0/src/stack.rs#L27) is just a very simple struct:

```rust
#[derive(Debug)]
pub struct Stack {
    top: *mut c_void,
    bottom: *mut c_void,
}
```

So yeah, it just contains two pointers! You can define **Any Struct** as you wish. LoL.

**Comment by dpc** [comment]
@zonyitoo : But `Stack` does not have any ownership. So if I created `ProtectedFixedSizeStack` how do I convert it to `Stack`, so I don't have to store both? (Basically I want `_stack : AnyStack` here: https://github.com/dpc/mioco/commit/3fa9c692f608cf50af3cabea6f3b6cd29d723f5b#diff-e9677ce240b391cd8d76f86bd76305d7R141

It seems to me there should be

```
trait Stack {
    fn top(&self) -> *mut c_void;
    fn bottom(&self) -> *mut c_void;
}
```

or

```
trait AsStack
    fn as_stack(&self) -> &Stack;
}
```
so I can have `Coroutine<S : Stack> { ... stack: S ... }` or `Coroutine<S : AsStack> { ... stack: S ... }` something like this.

I think context-rs should define such trait: it already has two versions of Stack, and it is going to be a standard for context/coroutines for Rust.

I'm OK with non-Copiable `Context` but maybe... unsafe `to_ptr()` and `from_ptr()` could be used as an escape hatch? 

Any idea why I haven't seen any speedup? Should I? Please add `NonZero` optimization to `Context` - maybe it will help.

**Comment by dpc** [comment]
Hmmm... Maybe no trait is needed...

I could just use `Coroutine<S : std::convert::AsRef<Stack>> { ... stack: S ... }` ...

**Comment by dpc** [comment]
I just went with `enum` ATM. Maybe I'm just over complicating.

**Comment by zonyitoo** [comment]
@dpc Looks good!

**Comment by dpc** [comment]
@zonyitoo : Does coroutine-rs#1.0 unwind on drop or anything like this? Is it documented?

**Comment by zonyitoo** [comment]
@dpc Unwinding is left for you. You can see it in the example: https://github.com/zonyitoo/context-rs/blob/1.0/examples/how_to_ontop.rs#L77

**Comment by dpc** [comment]
@zonyitoo: 
I'm just double checking if I'm not doing needless work.  I think I've understood that example now. It seems I can simplify mioco, as I was checking manually on every entrance if I should propagate panic, but now `resume_ontop` can it automatically for me.

Also it's one of a gotchas that are easy to overlook: dropping a context will keep resources allocated in it around without running drop on them.

**Comment by zonyitoo** [comment]
I was thinking about to add some helper facilities to do the unwinding job for users, the basic idea is to wrap the context function call with a `panic::recover` and will move the stack instance on the stack itself. When the context function is going to finish, unwind the stack and drop the stack properly.

This would make it "safe". :) Just for brain storming.

**Comment by dpc** [comment]
Mioco kind of does it already, and after catching with recover some manual maintenance is required, so context-rs doing it automatically would get in a way. The current ways are perfectly fine with mioco. Maybe a wrapper like `AutoContext` that has `Drop` implemented  would be useful for other projects that don't want to deal with it.

I think it's OK to leave it as is, as leaking memory is technically `safe` in Rust meaning of this word. I just think the need for unwinding should have a big fat warning, and be well documented. I myself find the current example not very readable.

But oh well, we're small and young projects so tutorial etc. will come later.
