### ISSUE TITLE
Spurious wakeup every 1000ms

### ISSUE THREAD

**Issue by sp3d** [dpc/mioco#95]
At lib.rs:669 (`Mioco::thread_loop`), Mioco unconditionally passes a timeout of `Some(1000)` to `event_loop.run_once`. This causes a wakeup every second, regardless of whether it's needed. There isn't any comment stating why a timeout is passed, and in my application it seems unnecessary based on testing with mioco patched to pass `None` there.

If I understand properly, there should be no reason to use a timeout since Mioco timers will produce an event when they go off. On the other hand, if there *is* something in the design of Mioco that necessitates waking up periodically, 1000ms seems like a hard interval to justify, and there should be a knob for this timeout for applications to tune.

**Comment by dpc** [comment]
I have it on my radar. I hopped no one is going to notice before it's fixed. :D . That was the original mio behavior - call `Handler::tick()` at least once a second.

The only reason it's there is to notice where whole mioco instance should shutdown. This needs to be changed to use notification (`Message`).
